const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const root=require('path').join(__dirname,'../dist/');const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'data.js','utf8'),ctx);
let result;const w={console,performance,TextEncoder,TextDecoder,URL,setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(root+'logic-cache.json'))}),self:{postMessage:r=>{result=r;}}};vm.createContext(w);vm.runInContext(fs.readFileSync(root+'checks-worker.js','utf8'),w);
(async()=>{await w.self.onmessage({data:{type:'init',data:ctx.window.RSL_DATA}});assert.equal(result.type,'ready',result.message);const items=result.items;
const state={values:{right2:'Off',right3:'Désactivé',right4:'Off',right12:'Off',right22:'Off',right23:'Désactivé',left15:'Désactivé',left21:'Désactivé'},notes:{},checks:{inventory:{},startAge:'child',assumeKeys:false,showOut:false}};
async function run(){await w.self.onmessage({data:{type:'evaluate',revision:1,state:JSON.parse(JSON.stringify(state))}});assert.equal(result.type,'result',result.message);return result.locations;}
const savedValues=state.values;state.values={};let fresh=await run();assert(fresh.some(l=>l.name==='KF Midos Top Left Chest'));assert(fresh.some(l=>l.name==='Kak Anju as Child'));assert(!fresh.some(l=>l.name==='Kak Anju as Adult'));state.values.left19='Activé';fresh=await run();assert(fresh.some(l=>l.name==='Kak Anju as Adult'));state.values.left19='Désactivé';state.checks.inventory={Ocarina:1};fresh=await run();assert(!fresh.some(l=>l.name==='Kak Anju as Adult'));state.checks.inventory['Song of Time']=1;fresh=await run();assert(fresh.some(l=>l.name==='Kak Anju as Adult'));state.checks.inventory={};state.values=savedValues;let ls=await run();assert(ls.some(l=>l.name==='KF Midos Top Left Chest'));assert(!ls.some(l=>['Freestanding','GS Token','Shop','GrottoScrub','Song'].includes(l.type)));assert(!ls.some(l=>/Grass|EnemyDrop|GossipStone/.test(l.type)));
for(const count of [0,10,20,30,40,50]){state.checks.inventory['Gold Skulltula Token']=count;ls=await run();assert.equal(ls.filter(l=>/^Kak (10|20|30|40|50) Gold Skulltula Reward$/.test(l.name)).length,count/10);}delete state.checks.inventory['Gold Skulltula Token'];
state.checks.inventory={'Lens of Truth':1};ls=await run();assert(!ls.some(l=>l.name==='Market Treasure Chest Game Reward'));state.checks.inventory['Magic Meter']=1;ls=await run();assert(ls.some(l=>l.name==='Market Treasure Chest Game Reward'&&l.age==='child'));state.values.right17='Sanity';ls=await run();assert(!ls.some(l=>l.name==='Market Treasure Chest Game Reward'));delete state.checks.assumeKeys;ls=await run();assert(ls.some(l=>l.name==='Market Treasure Chest Game Reward'));state.checks.assumeKeys=false;ls=await run();assert(!ls.some(l=>l.name==='Market Treasure Chest Game Reward'));state.checks.inventory['Small Key (Treasure Chest Game)']=6;ls=await run();assert(ls.some(l=>l.name==='Market Treasure Chest Game Reward'));state.values.right17='Vanilla';state.checks.inventory={};
state.checks.inventory.Slingshot=1;ls=await run();assert(ls.some(l=>l.name==='LW Target in Woods'));delete state.checks.inventory.Slingshot;ls=await run();assert(!ls.some(l=>l.name==='LW Target in Woods'));
state.values.right5='Overworld';ls=await run();assert(ls.some(l=>l.type==='Freestanding'));assert(!ls.some(l=>l.type==='Freestanding'&&/Temple|Deku Tree/.test(l.name)));state.values.right5='';ls=await run();assert(!ls.some(l=>l.type==='Freestanding'));
state.values.right4='Simple';ls=await run();assert(!ls.some(l=>l.name==='KF Midos Top Left Chest'));state.notes['Indoors:24']='KF Mido';ls=await run();assert(ls.some(l=>l.name==='KF Midos Top Left Chest'));state.notes['Indoors:24']='unrecognized';ls=await run();assert(!ls.some(l=>l.name==='KF Midos Top Left Chest'));assert(result.unresolved.includes('unrecognized'));
state.values.right4='Simple';state.notes={'Indoors:24':'Great Fairy'};state.checks.inventory={Ocarina:1,'Zeldas Lullaby':1};ls=await run();assert(!result.unresolved.includes('Great Fairy'));assert(ls.some(l=>l.label.startsWith('Great Fairy ·')));state.values.right4='Off';state.values.right3='Activé';state.notes={'Grottos:2':'Generic grotto','Grottos:27':'Generic grotto'};state.checks.inventory={Bottle:1};ls=await run();assert(!result.unresolved.includes('Generic grotto'));assert.equal(ls.filter(l=>l.label.startsWith('Generic grotto ·')).length,2);
state.notes={};state.checks.inventory=Object.fromEntries(items.map(i=>[i.name,i.max]));for(const s of ctx.window.RSL_DATA.settings)if(s.type==='bool')state.values[s.id]='Activé';Object.assign(state.values,{right2:'Off',right3:'Désactivé',right4:'Off',right12:'Off',left15:'Désactivé',left21:'Désactivé',right5:'All',right7:'Affordable',right6:'4',right15:'Anywhere',right10:'Keysy',right11:'Keysy',left3:'Remove',left11:'Remove',right22:'Off',left2:'Open',left6:'All'});ls=await run();assert(ls.length>300);assert(ls.filter(l=>l.type==='Shop').length<=32);assert(ls.some(l=>l.type==='SilverRupee'));const silverCounts={};for(const mode of ['Remove','Dungeon','Overworld','Regional','Anywhere','Vanilla','']){state.values.left11=mode;const all=await run();silverCounts[mode||'unknown']=all.filter(l=>l.type==='SilverRupee').length;if(mode&&mode!=='Vanilla'){for(const zone of ['Ice Cavern','Bottom of the Well','Shadow Temple','Spirit Temple','Gerudo Training Ground',"Ganon's Castle"]){assert(all.some(l=>l.type==='SilverRupee'&&l.zone===zone),mode+' '+zone);}}else assert.equal(silverCounts[mode||'unknown'],0);}assert.equal(silverCounts.Remove,silverCounts.Anywhere);console.log('Silver checks by mode:',silverCounts);
state.values={left19:'Activé',left24:'Activé',left11:'Anywhere'};state.notes={};state.checks.inventory={'Progressive Scale':1,Ocarina:1,'Zeldas Lullaby':1,Bottle:1};state.checks.showOut=false;let ice=await run();assert.equal(ice.filter(l=>l.name.startsWith('Ice Cavern Spinning Scythe Silver Rupee')).length,5);assert(!ice.some(l=>l.name==='Ice Cavern Map Chest'));state.values.left11='Remove';ice=await run();assert.equal(ice.filter(l=>l.name.startsWith('Ice Cavern Spinning Scythe Silver Rupee')).length,5);assert(ice.some(l=>l.name==='Ice Cavern Map Chest'));state.values.left11='Vanilla';ice=await run();assert(!ice.some(l=>l.type==='SilverRupee'));assert(ice.some(l=>l.name==='Ice Cavern Map Chest'));state.values.left11='';ice=await run();assert(!ice.some(l=>l.type==='SilverRupee'));assert(ice.some(l=>l.name==='Ice Cavern Map Chest'));state.values.left11='Anywhere';state.checks.inventory['Silver Rupee Pouch (Ice Cavern Spinning Scythe)']=1;ice=await run();assert(ice.some(l=>l.name==='Ice Cavern Map Chest'));assert.equal(ice.filter(l=>l.name.startsWith('Ice Cavern Push Block Silver Rupee')).length,5);
state.values={left19:'Activé'};state.notes={};state.checks.inventory={};state.checks.showOut=false;const base=await run();state.checks.showOut=true;const expanded=await run();assert(expanded.length>base.length);for(const l of base){assert(expanded.some(e=>e.name===l.name&&!e.out));}assert(expanded.some(l=>l.out));assert(!expanded.some(l=>['Freestanding','GS Token','Shop','Song'].includes(l.type)));state.checks.showOut=false;const restored=await run();assert.equal(restored.length,base.length);assert(!restored.some(l=>l.out));console.log('Out checks:',expanded.filter(l=>l.out).map(l=>l.name));console.log('Worker checks passed:',ls.length,'reachable with full inventory; settings filters, item removal, ER and unknown destinations verified');})();
