import {WorldGraphFactory} from '@mracsys/randomizer-graph-tool';
export const LOGIC_VERSION='8.2.52 Rob-132';
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const active=v=>!['','inconnu','off','desactive','false','vanilla','none','0'].includes(norm(v));
const indoors=['Market Guard House','Market Bazaar','Market Potion Shop','Temple of Time','Market Mask Shop','Market Shooting Gallery','Market Bombchu Bowling','Market Treasure Chest Game','Market Bombchu Shop','Market Man in Green House','Kak Carpenter Boss House','Kak Bazaar','Kak Potion Shop Front','Kak Potion Shop Back','Kak Odd Medicine Building','Kak Windmill','Kak Impas House Back','Kak Impas House','Kak Shooting Gallery','Kak House of Skulltula',null,'KF Midos House','KF Know It All House','KF Links House','KF Sarias House','KF House of Twins','KF Kokiri Shop','LLR Talons House','LLR Stables','LLR Tower','LH Lab','LH Fishing Hole','GV Carpenter Tent','Colossus Great Fairy Fountain','HC Great Fairy Fountain','OGC Great Fairy Fountain','Graveyard Dampes House','GC Shop','DMT Great Fairy Fountain','DMC Great Fairy Fountain','ZD Shop','ZF Great Fairy Fountain'];
const grottos=['Colossus Grotto','HC Storms Grotto','Kak Open Grotto','Kak ReDead Grotto','Graveyard Shield Grave','Graveyard Dampes Grave','Graveyard Heart Piece Grave','Graveyard Royal Familys Tomb','DMT Storms Grotto','DMT Cow Grotto','GC Grotto','DMC Hammer Grotto','DMC Upper Grotto','ZR Storms Grotto','ZR Open Grotto','ZR Fairy Grotto','ZD Storms Grotto','LLR Grotto','LH Grotto','KF Storms Grotto','LW Near Shortcuts Grotto','LW Scrubs Grotto','Deku Theater','SFM Wolfos Grotto','SFM Fairy Grotto','SFM Storms Grotto','HF Southeast Grotto','HF Open Grotto','HF Inside Fence Grotto','HF Cow Grotto','HF Near Market Grotto','HF Fairy Grotto','HF Tektite Grotto','HF Near Kak Grotto','GV Octorok Grotto','GV Storms Grotto','GF Storms Grotto'];
const dungeons=['Deku Tree Lobby','Dodongos Cavern Beginning','Jabu Jabus Belly Beginning','Forest Temple Lobby','Fire Temple Lower','Water Temple Lobby','Shadow Temple Entryway','Spirit Temple Lobby','Ice Cavern Beginning','Gerudo Training Ground Lobby','Bottom of the Well','Ganons Castle Lobby'];
const bosses=['Queen Gohma','King Dodongo','Barinade','Phantom Ganon','Volvagia','Morpha','Bongo Bongo','Twinrova'];
const warps=['Minuet of Forest','Bolero of Fire','Serenade of Water','Requiem of Spirit','Nocturne of Shadow','Prelude of Light'];
const CATEGORIES={tokensanity:{Vanilla:'off',DG:'dungeons',OW:'overworld',All:'all'},shuffle_freestanding_items:{Dungeon:'dungeons'},shuffle_scrubs:{Vanilla:'off',Affordable:'low',Expensive:'regular',Random:'random'},shuffle_song_items:{Songs:'song',Reward:'dungeon',Anywhere:'any'},shuffle_enemy_spawns:{Bosses:'bosses',Regional:'regional'},shuffle_smallkeys:{Keysy:'remove',DG:'dungeon',OW:'overworld',Sanity:'keysanity',Regional:'regional'},shuffle_bosskeys:{Keysy:'remove',DG:'dungeon',Sanity:'keysanity',Regional:'regional'},shuffle_ganon_bosskey:{Remove:'remove',DG:'dungeon',OW:'overworld','Any DG':'any_dungeon',Sanity:'keysanity',LACS:'on_lacs',Meds:'medallions',Rewards:'dungeons'},shuffle_mapcompass:{'Start with':'startwith',DG:'dungeon',OW:'overworld','Any DG':'any_dungeon',Sanity:'keysanity'},shuffle_tcgkeys:{Sanity:'keysanity'},bridge:{Meds:'medallions',Dungeon:'dungeons'},scarecrow_behavior:{Activé:'free',Désactivé:'vanilla'}};
const UNKNOWN={shuffle_tcgkeys:'vanilla',damage_multiplier:'double',plant_beans:false,open_forest:'closed_deku',bridge:'medallions',bridge_medallions:6,gerudo_fortress:'normal',zora_fountain:'closed',open_door_of_time:false,shuffle_interior_entrances:'off',shuffle_grotto_entrances:false,shuffle_dungeon_entrances:'off',shuffle_bosses:'off',shuffle_smallkeys:'keysanity',shuffle_bosskeys:'keysanity',shuffle_ganon_bosskey:'keysanity',shuffle_silver_rupees:'anywhere',shuffle_enemy_spawns:'off',shuffle_individual_ocarina_notes:false,shuffle_song_items:'any',shuffle_mapcompass:'dungeon',shuffle_freestanding_items:'off',shuffle_scrubs:'off',shopsanity:'off',tokensanity:'off',shuffle_ocarinas:false,shuffle_kokiri_sword:false,shuffle_cows:false,shuffle_frog_song_rupees:false,shuffle_beans:false,shuffle_gerudo_card:false,shuffle_expensive_merchants:false,warp_songs:true,owl_drops:true};
const GROUP_ZONES={'Lost Woods Maze':'Lost Woods','Market Square':'Market','Market Entrance':'Market','Temple of Time Entrance':'Market','Outside Ganon\'s Castle':'Ganon\'s Castle','Castle Grounds':'Hyrule Castle'};
export class ChecksEngine{
 constructor(cache,data){this.data=data;this.graph=WorldGraphFactory('ootr',{settings:{graphplugin_world_search_mode:'starting_items'},locations:{}},LOGIC_VERSION,cache);this.defs=this.graph.get_settings_options();this.lastConfig='';this.allItems=Object.entries(this.graph.ItemInfo.items).filter(([n,i])=>i.advancement&&!['Event','Drop','Shop','Fish'].includes(i.type)&&!n.includes('???')).map(([name,i])=>({name,type:i.type,max:this.itemMax(name,i)}));}
 itemMax(n,i){if(n==='Gold Skulltula Token')return 100;if(n==='Heart Container')return 17;if(n==='Piece of Heart')return 36;if(n==='Triforce Piece')return 100;if(n.startsWith('Small Key ('))return {'Forest Temple':5,'Fire Temple':8,'Water Temple':6,'Shadow Temple':5,'Spirit Temple':5,'Bottom of the Well':3,'Gerudo Training Ground':9,'Ganons Castle':2,'Thieves Hideout':4,'Treasure Chest Game':6}[n.slice(11,-1)]??9;if(n.startsWith('Silver Rupee ('))return 10;if(n.startsWith('Bottle'))return 4;return Math.min(10,i.special?.progressive??1);}
 settings(state){const v=state.values,settings={};for(const [key,weights] of Object.entries(this.data.rslPreset.weights)){const values=Object.entries(weights).filter(([,n])=>n>0);if(values.length===1&&this.defs[key]){let x=values[0][0];settings[key]=this.defs[key].type==='bool'?x==='true':this.defs[key].type==='int'?Number(x):x;}}
 Object.assign(settings,UNKNOWN);for(const s of this.data.settings){let key=s.presetKey;if(!key||!this.defs[key])continue;const value=v[s.id];if(value===undefined||value==='')continue;let x=CATEGORIES[key]?.[value]??String(value).toLowerCase().replaceAll(' ','_');const def=this.defs[key];if(def.type==='bool')x=active(value);else if(def.type==='int')x=Number(value);else if(def.choices&&!Object.hasOwn(def.choices,x))continue;settings[key]=x;}
 // Older RSL branches use boolean names for these two options.
 if(this.defs.free_scarecrow)settings.free_scarecrow=active(v.left16);
 settings.zora_fountain=active(v.left24)?'open':'closed';settings.shuffle_child_trade=active(v.right16)?['Weird Egg']:[];
 for(const [id,key] of [['left2','bridge'],['left3','ganon_bosskey']]){const count=Number(v[id+':count']);if(v[id+':count']!==undefined&&v[id+':count']!==''&&Number.isFinite(count)){for(const type of ['medallions','stones','rewards','tokens','hearts'])settings[key+'_'+type]=count;}}
 settings.starting_age=state.checks?.startAge??'child';settings.starting_items={...(state.checks?.inventory??{})};if(state.checks?.assumeKeys!==false){for(const item of this.allItems)if(/^(Small Key|Boss Key) \(/.test(item.name))settings.starting_items[item.name]=item.max;}if(settings.open_door_of_time)settings.starting_items['Time Travel']=1;if(settings.blue_fire_arrows&&settings.starting_items['Ice Arrows'])settings.starting_items['Blue Fire Arrows']=1;
 settings.allowed_tricks=this.data.rslPreset.options.tricks.filter(t=>!this.defs.allowed_tricks?.choices||Object.hasOwn(this.defs.allowed_tricks.choices,t));settings.graphplugin_world_search_mode='starting_items';settings.graphplugin_viewable_unshuffled_items=Object.keys(this.defs.graphplugin_viewable_unshuffled_items.choices);settings.graphplugin_region_visibility_mode='matching';settings.mq_dungeons_specific=[];settings.spawn_positions=[];settings.mix_entrance_pools=[];settings.decouple_entrances=false;settings.shuffle_boulders=active(v.right18);settings.shuffle_pots='off';settings.shuffle_crates='off';settings.shuffle_beehives=false;settings.shuffle_fishing_rod=false;settings.dungeon_shortcuts=[];
 const shortcuts=String(v.left10??'').toLowerCase();for(const [name,aliases] of Object.entries({'Deku Tree':['deku'],'Dodongos Cavern':['dc','dodongo'],'Jabu Jabus Belly':['jabu'],'Forest Temple':['forest'],'Fire Temple':['fire'],'Water Temple':['water'],'Shadow Temple':['shadow'],'Spirit Temple':['spirit']})){if(aliases.some(a=>new RegExp('(^|[ ,;/])'+a+'($|[ ,;/])').test(shortcuts)))settings.dungeon_shortcuts.push(name);}
 if(settings.shuffle_silver_rupees!=='vanilla'&&settings.shuffle_silver_rupees!=='remove')settings.silver_rupee_pouches_choice='all';
 // Do not infer inventory from the unshuffled token locations.
 settings.tokensanity='all';
 return settings;}
 connect(state){const w=this.graph.worlds[0],notes=state.notes,all=w.get_entrances(),forward=all.filter(e=>e.type&&!e.is_reverse()),byRegion=region=>forward.find(e=>e.original_connection?.name===region&&!['Spawn','WarpSong','BlueWarp'].includes(e.type));const aliasMap=new Map();
 const add=(label,e)=>{if(!label||!e)return;const key=norm(label);if(!aliasMap.has(key))aliasMap.set(key,e);else if(aliasMap.get(key)?.original_connection!==e.original_connection)aliasMap.set(key,null);};
 for(const e of forward){add(e.name,e);add(e.original_connection?.name,e);add(e.alias,e);}
 for(const [names,regions] of [[this.data.indoors,indoors],[this.data.grottos,grottos],[this.data.dungeons,dungeons]])names.forEach((n,i)=>add(n,byRegion(regions[i])));
 for(const [short,region] of Object.entries({KF:'Kokiri Forest',LW:'Lost Woods',SFM:'Sacred Forest Meadow',HF:'Hyrule Field',KAK:'Kakariko Village',GY:'Graveyard',DMT:'Death Mountain',GC:'Goron City',DMC:'DMC Central Local',ZR:'Zora River',ZD:'Zoras Domain',ZF:'Zoras Fountain',LH:'Lake Hylia',LLR:'Lon Lon Ranch',GV:'GV Fortress Side',GF:'Gerudo Fortress',Colossus:'Desert Colossus',ToT:'Temple of Time'})){const e=forward.find(e=>e.original_connection?.name===region);if(e)aliasMap.set(norm(short),e);}
 this.genericLocations=new Map();const used=new Set();for(const text of Object.values(notes)){const target=aliasMap.get(norm(text));if(target)used.add(target);}
 const unresolved=[];const connect=(source,text)=>{if(!text)return;if(!source){unresolved.push(text);return;}if(!source.shuffled)return;const generic=norm(text);if(['greatfairy','genericgrotto'].includes(generic)){const target=forward.find(e=>!used.has(e)&&(generic==='greatfairy'?e.original_connection?.name.includes('Great Fairy Fountain'):e.original_connection?.locations.some(l=>l.name.endsWith('Grotto Chest'))&&e.original_connection?.locations.some(l=>l.name.includes('Lone Fish'))));if(target){used.add(target);this.graph.set_entrance(source,target);const region=source.connected_region;for(const l of region.locations)if(l.type==='Chest'||l.name.includes('Great Fairy Reward'))this.genericLocations.set(l.name,{name:text+':'+source.name,label:text+' · '+source.name.split(' -> ')[0]});return;}unresolved.push(text);return;}const target=['v','vanilla'].includes(norm(text))?source:aliasMap.get(norm(text));if(target&&target.original_connection){this.graph.set_entrance(source,target);}else unresolved.push(text);};
 this.data.indoors.forEach((n,i)=>connect(byRegion(indoors[i]),notes['Indoors:'+i]));this.data.grottos.forEach((n,i)=>connect(byRegion(grottos[i]),notes['Grottos:'+i]));this.data.dungeons.forEach((n,i)=>connect(byRegion(dungeons[i]),notes['dungeon:'+i]));
 this.data.dungeons.forEach((n,i)=>{const source=byRegion(dungeons[i]),inside=source?.connected_region?.dungeon??source?.connected_region?.name;const boss=notes['boss:'+i];if(!boss||boss==='aucun')return;const target=forward.find(e=>/Boss$/.test(e.type)&&norm(e.alias)===norm(boss==='Gohma'?'Queen Gohma':boss));const bossEntrance=forward.find(e=>['ChildBoss','AdultBoss'].includes(e.type)&&e.parent_region?.dungeon===inside);if(bossEntrance?.shuffled&&target)this.graph.set_entrance(bossEntrance,target);});
 warps.forEach((name,i)=>connect(forward.find(e=>e.type==='WarpSong'&&e.alias===name),notes['Warp songs:'+i]));connect(forward.find(e=>e.name==='LH Owl Flight -> Hyrule Field'),notes['Owl drops:0']);connect(forward.find(e=>e.name==='DMT Owl Flight -> Kak Impas Rooftop'),notes['Owl drops:1']);
 // Explicit start destinations take precedence over their vanilla spawn.
 for(const [i,age] of ['child','adult'].entries()){const text=notes['spawn:'+i];if(text){const source=forward.find(e=>e.type==='Spawn'&&e.name.startsWith(age==='child'?'Child':'Adult'));const target=aliasMap.get(norm(text));if(source&&target)this.graph.set_entrance(source,target);else if(source){source.disconnect();unresolved.push('Spawn '+age+' : '+text);}}}
 return unresolved;}
 categoryAllowed(l,state){const v=state.values,n=l.name,t=l.type,dungeon=!!l.parent_region?.dungeon;
 if(!l.rslShuffled||!['Chest','Collectable','NPC','Cutscene','BossHeart','Boss','Song','Shop','GS Token','Freestanding','ActorOverride','Scrub','GrottoScrub','SilverRupee'].includes(t)||l.internal||l.is_hint||['Event','Drop','GraphEvent','Hint','HintInternal','HintStone','Pot','Crate','Beehive','Fish','RupeeTower','Wonderitem'].includes(t)||n.includes('Shop Invisible Rupee'))return false;
 if(t==='Freestanding'||t==='ActorOverride'){const mode=String(v.right5??'').toLowerCase();return mode==='all'||(dungeon?mode==='dungeon':mode==='overworld');}
 if(t==='GS Token'){const mode=String(v.left6??'').toLowerCase();return mode==='all'||(dungeon?mode==='dg':mode==='ow');}
 if(['Scrub','GrottoScrub'].includes(t)&&!active(v.right7)&&!['LW Deku Scrub Near Bridge','LW Deku Scrub Grotto Front','HF Deku Scrub Grotto'].includes(n))return false;
 if(t==='SilverRupee'&&(!active(v.left11)||v.left11==='Remove'))return false;
 if(t==='Shop'){if(!active(v.right6)||l.holds_shop_refill)return false;const shopPrefixes=['KF Shop','Market Bazaar','Market Potion Shop','Market Bombchu Shop','Kak Bazaar','Kak Potion Shop','GC Shop','ZD Shop'],shop=shopPrefixes.indexOf(n.replace(/ Item \d+$/,'')),slot=[7,5,8,6].indexOf(Number(n.match(/\d+$/)?.[0]));if(shop<0||slot<0)return false;const key=slot===0?'shop:'+shop:'shop:'+shop+':item:'+slot,price=state.notes['shop:'+shop+':price:'+slot];if(v.right6==='Random'&&!state.notes[key]&&(price===undefined||price===''))return false;const cost=price!==undefined&&price!==''?Number(price):Number(v['right6:priceMax']||200);const wallet=[99,200,500,999][Math.min(3,Number(state.checks?.inventory?.['Progressive Wallet']??0))];if(cost>wallet)return false;}
 if(t==='Song'&&!active(v.right15))return false;
 if(/Cow$/.test(n)&&!active(v.right14))return false;
 if(n==='KF Kokiri Sword Chest'&&!active(v.right9))return false;
 if(/(?:Ocarina|Ocarina of Time Item)$/.test(n)&&!active(v.right8))return false;
 if(n==='ZR Magic Bean Salesman'&&!active(v.right20))return false;
 if(n==='Hideout Gerudo Membership Card'&&!active(v.right21))return false;
 if(/Frogs (Zeldas|Eponas|Sarias|Suns|Song of Time)/.test(n)&&!active(v.right19))return false;
 if(['GC Medigoron','Wasteland Bombchu Salesman','Kak Granny Buy Blue Potion'].includes(n)&&!active(v.left14))return false;
 if(/Malon Egg/.test(n)&&!active(v.right16))return false;
 if(t==='MaskShop')return false;
 return true;}
 evaluate(state){const settings=this.settings(state);const config=JSON.stringify({settings,boulders:state.checks?.boulders,notes:Object.fromEntries(Object.entries(state.notes).filter(([k])=>/^(Indoors:|Grottos:|dungeon:|boss:|Warp songs:|Owl drops:|spawn:|trial:|soul:|shop:)/.test(k)))});if(config!==this.lastConfig){const trials={};for(const name of ['Forest','Fire','Water','Spirit','Shadow','Light'])trials[name]=state.notes['trial:'+name]==='Non requis'?'inactive':'active';this.graph.import({settings,locations:{},entrances:{},trials});this.unresolved=this.connect(state);if(active(state.values.right18)){for(const [name,type] of Object.entries(state.checks?.boulders??{})){const b=this.graph.worlds[0].boulders.find(b=>b.name===name);if(b)this.graph.set_boulder_type(b,[0,1,2,3].includes(Number(type))?Number(type):null);}}
 const w=this.graph.worlds[0];const tcg=w.get_locations().find(l=>l.name==='Market Treasure Chest Game Reward');if(tcg){tcg.rslOriginalRule??=tcg.access_rule;tcg.access_rule=w.settings.shuffle_tcgkeys==='vanilla'?((s,{age=null}={})=>age==='child'&&s.has('Magic Meter')&&s.has('Lens of Truth')):tcg.rslOriginalRule;}for(const l of w.get_locations()){l.rslShuffled=l.shuffled;if(!['Event','Drop'].includes(l.type)&&!l.internal&&l.type!=='Shop'){l.item=null;l.shuffled=true;}}
 // Souls recorded in Race belong to the boss occupying that dungeon.
 if(active(state.values.right22)){this.data.dungeons.forEach((d,i)=>{if(state.notes['soul:'+i]!==true)return;let boss=state.notes['boss:'+i];if(!active(state.values.right12)){const dungeon=active(state.values.right2)?this.data.dungeons.indexOf(state.notes['dungeon:'+i]):i;boss=bosses[dungeon];}if(boss==='Gohma')boss='Queen Gohma';const soul=Object.keys(this.graph.ItemInfo.items).find(n=>norm(n)===norm(boss+' Soul'));if(soul)w.settings.starting_items[soul]=1;});}
 this.graph.reset_searches();this.graph.search.collect_locations(w.get_locations());this.lastConfig=config;}
 const w=this.graph.worlds[0],locations=[];for(const l of w.get_locations()){if(!this.categoryAllowed(l,state))continue;const child=this.graph.search.spot_access(l,'child'),adult=this.graph.search.spot_access(l,'adult');if(!child&&!adult)continue;let zone=l.hint_area||l.parent_region?.dungeon||l.parent_region?.name||'Autres';zone=GROUP_ZONES[zone]??zone;const generic=this.genericLocations?.get(l.name);locations.push({name:generic?.name??l.name,label:generic?.label??(l.type==='Shop'?l.name.replace(/ Item \d+$/, ' · item '+([7,5,8,6].indexOf(Number(l.name.match(/\d+$/)?.[0]))+1)):l.name),zone,type:l.type,age:child&&adult?'both':child?'child':'adult'});}
 return {locations,unresolved:this.unresolved??[],unknownEntrances:['right2','right3','right4','right12'].filter(id=>!state.values[id]).length};}
}
